### ISSUE TITLE
How will a visitor to the webpage/app navigate through the site?

### ISSUE THREAD

**Issue by KirstieJane** [KirstieJane/STEMMRoleModels#14]
Erin (@erich001) has made a kickass schematic of how a visitor might navigate through the site: 
https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/conceptualdesign.pdf

If you have any comments or suggestions please add them below!

**Comment by Ryuno-Ki** [comment]
Where's that "kickass schematic"? It's an [user journey](https://en.wikipedia.org/wiki/User_journey) isn't it?

Could be helpful for designing the layout/prioritising elements.

**Comment by Ryuno-Ki** [comment]
The schematic from #20?

https://github.com/KirstieJane/STEMMRoleModels/blob/master/SchematicDesign/conceptualdesign.pdf
-> 404 due to missing `master` branch. New location at https://github.com/KirstieJane/STEMMRoleModels/blob/d1c5d38844c823fa5f6cd994ed6662542ea32116/SchematicDesign/conceptualdesign.pdf

(If so, please hit <kbd>y</kbd> to get an URL which points to a file frozen in time, hit <kbd>?</kbd> for more shortcuts on GitHub).

**Comment by KirstieJane** [comment]
Added the link back in! Thank you @Ryuno-Ki :smiley:

**Comment by KirstieJane** [comment]
Closing this issue! Thank you @erich001 :grinning:
