### ISSUE TITLE
Add title image (icon) in the website

### ISSUE THREAD

**Issue by raj-maurya** [KirstieJane/STEMMRoleModels#89]
A title image (icon) needs to be added.

**Comment by KirstieJane** [comment]
Hi @raj-maurya! Thank you so much for contributing to the STEMM Role Models project.

I'm travelling at the moment and don't have time to review your pull request but I'll find some tomorrow and get you some feedback!

Thanks again for contributing :balloon:

**Comment by raj-maurya** [comment]
@KirstieJane thanks for the consideration.

Looking forward for your feedback.

**Comment by KirstieJane** [comment]
Thanks so much @raj-maurya. I've merged your pull request #88 because it looks great for the [index.html](http://stemmrolemodels.com/) page that we have right now.

There are two additional goals that would be great:

1) We need to add this icon to the other pages in the [site](https://github.com/KirstieJane/STEMMRoleModels/tree/gh-pages/site) folder because they're the ones we'll be moving to once we launch the real website.

2) The image is too detailed to be a good icon. @neuroAmyo - do you have any suggestions for how to make it more appropriate? It now turns up in the tab when you load the [stemmrolemodels](http://stemmrolemodels.com/) website.

On top of that, @raj-maurya - can you tell me how you made the [images/stemm.ico](https://github.com/KirstieJane/STEMMRoleModels/blob/gh-pages/images/stemm.ico) file?

Thanks again for spotting that we needed this :smile: :balloon: :cake:

**Comment by raj-maurya** [comment]
Thank you @KirstieJane 

I will add the title bar icon on other pages that are in the [site](https://github.com/KirstieJane/STEMMRoleModels/tree/gh-pages/site) folder asap ( issue #89) and will give a pull request for the same.

If you could provide the compatible logo (icon) it will help me to fix this issue completely .

Thanks again!

**Comment by raj-maurya** [comment]
@KirstieJane 

You can use any appropriate online icon generator, the most compatible dimension used for title icon is 16x16.

Some online icon generator websites. (free) :+1: 
1.http://icoconvert.com/
2.http://www.favicon-generator.org/ 

Thanks!

**Comment by KirstieJane** [comment]
Thank you for the recommendations on where to make the icons @raj-maurya! That saves me trying to figure out which ones work well etc! :balloon: 

I'm going to leave this issue open while we wait to see if @neuroAmyo has any time to make a smaller image. But I'm off to check PR #91 now....

**Comment by neuroAmyo** [comment]
I took a stab at an icon: STEMMRoleModels/SchematicDesign/webIcon_160911.png I also uploaded a .ico version made via icoconvert.com that includes 16x16, 32x32, 48x48, and 256x256 sizes. Still learning about how these icons work so let me know if people have thoughts on how to optimize the graphics. Thanks for the link @raj-maurya !

**Comment by KirstieJane** [comment]
Done! Thank you @neuroAmyo and @raj-maurya! Icon looks great!
