### ISSUE TITLE
Add navigation-bar to the website.

### ISSUE THREAD

**Issue by raj-maurya** [KirstieJane/STEMMRoleModels#93]
We need to add navigation bar so as to have smooth access and better User Interface, experience to [http://stemmrolemodels.com/](http://stemmrolemodels.com/)

**Comment by raj-maurya** [comment]
Hi @KirstieJane 

I have tried to make the prototype of the navigation bar on my local server.
I have attached screenshots of the website after adding navigation bar also it is responsive (works smoothly on variable size screens).

I need feedback on this.

![screenshot from 2016-09-07 00-29-00](https://cloud.githubusercontent.com/assets/9070249/18312595/2e33d9c6-7528-11e6-8e4c-3c35b6c673e1.png)

![screenshot from 2016-09-07 00-29-54](https://cloud.githubusercontent.com/assets/9070249/18312626/5275ed74-7528-11e6-80f4-86c1e05c35ed.png)

![screenshot from 2016-09-07 00-32-29](https://cloud.githubusercontent.com/assets/9070249/18312640/608ef07c-7528-11e6-944d-dbca875c55aa.png)

![screenshot from 2016-09-07 00-33-22](https://cloud.githubusercontent.com/assets/9070249/18312654/708d4a82-7528-11e6-8cc8-238a2e306ce6.png)

Thanks!
Raj

**Comment by KirstieJane** [comment]
Hi @raj-maurya! Thank you for doing this work. Unforunately you're editing the placeholder website rather than the main one we're looking to launch which is in the [site](https://github.com/KirstieJane/STEMMRoleModels/tree/gh-pages/site) folder.

It might be really helpful for you to take a look at the nav bar on those pages though. We need to get rid of "login" and "join" and replace them with a search link (see #83 ) I'd really love for there to be a home button (see #69 ).

Let me know what you think about working on those issues instead!

**Comment by raj-maurya** [comment]
Thanks @KirstieJane !
I got it, and will work on it.

**Comment by KirstieJane** [comment]
Hi @raj-maurya - I've added in a nav bar on the pages - thank you for inspiring the issue!
